### ISSUE TITLE
Mess with endpoints

### ISSUE THREAD

**Issue by peerchemist** [virtualeconomy/felix_frontend#104]
https://github.com/theimmutabledao/felix_frontend/blob/master/src/api/request.js#L7

This mess here must be resolved, any reason why does it not read relevant endpoint from `vue.config.js`?

**Comment by jwzheng96** [comment]
The relevant endpoint is read from vue.config.js when we run the code locally. When deployed in production, the relevant endpoint is read from request.js. The devServer in vue.config.js is the local configuration. You can just focus on request.js.
