### ISSUE TITLE
DARA balance switch in config

### ISSUE THREAD

**Issue by peerchemist** [virtualeconomy/felix_frontend#106]
https://github.com/virtualeconomy/felix_frontend/blob/950e7241bec8e9197f70a8b3fd8e71a1b06b7aa7/src/views/WordPay.vue#L47

Can I please have this in config?
5000, 1000, 0. So it is easy to find and tweak.

**Comment by Haynar216** [comment]
https://github.com/virtualeconomy/felix_frontend/commit/0e2f121b6eb73c5a77a2282a7060d482c0812897
