### ISSUE TITLE
Upon a mint, explorer link leads to testnet explorer

### ISSUE THREAD

**Issue by peerchemist** [virtualeconomy/felix_frontend#107]
![image](https://user-images.githubusercontent.com/7818961/159257283-7db72369-e6dc-4778-92db-5c683370ce5b.png)

https://testexplorer.v.systems/transactions/63hFJwb272jXKpwcJFQymCrX9xjAzbsgYBVwMxubqwWj

**Comment by Xavier-Gao** [comment]
It's done.Please check!

**Comment by peerchemist** [comment]
![image](https://user-images.githubusercontent.com/7818961/160430912-bdfebcfa-df41-406c-ac47-0899e8c59d66.png)

It leads to "null" now? :(

https://explorer.v.systems/transactions/null

**Comment by Xavier-Gao** [comment]
<img width="525" alt="image" src="https://user-images.githubusercontent.com/46206733/160570277-d6008e43-fe75-40d7-8f1e-66d9ff170978.png">

I can't reproduce this situation. I got the '7VTbrhC2K9NJCPMmPGG7SscriE3bDzp1QMDZyMja9LAe'

[https://explorer.v.systems/transactions/7VTbrhC2K9NJCPMmPGG7SscriE3bDzp1QMDZyMja9LAe](url)

**Comment by Haynar216** [comment]
The transaction records returned by backend are not the mainnet, but on testnet
