### ISSUE TITLE
word is already saved - show 

### ISSUE THREAD

**Issue by marijacin** [virtualeconomy/felix_frontend#30]
on figma i showed example. if a word is saved, we should show it right away. peerchemist has code for this. just add the front end part

![image](https://user-images.githubusercontent.com/86068985/151699523-de5fa486-e178-4e52-bc29-e05659cd7ece.png)

**Comment by peerchemist** [comment]
This information is available in each lemma.

```
  {
    "id": 1178543,
    "etymology_no": 0,
    "definition": "(uncountable) A state in which opposing forces harmonise; equilibrium.",
    "nfthash": null,
    "definition_no": 0,
    "word": "balance",
    "lexical_category": "Noun",
    "blockchainhash": null
  },
  ```
  
If `blockchainhash` is not null it means it's saved.
If `nfthash` is no not null, it means NFT has been made.

**Comment by jwzheng96** [comment]
fixed
