### ISSUE TITLE
hover over buttons

### ISSUE THREAD

**Issue by marijacin** [virtualeconomy/felix_frontend#33]
i think its really important for user to know what are links/buttons, and what is non-clickable. 

![image](https://user-images.githubusercontent.com/86068985/151699769-be4d172e-bfd9-45ed-b35c-fb97bfb619aa.png)

**Comment by marijacin** [comment]
another example
![image](https://user-images.githubusercontent.com/86068985/153029546-4b585208-958c-468c-a92c-8ab17ad32089.png)

**Comment by Haynar216** [comment]
Fixed
