### ISSUE TITLE
Missing feature in settings - LIST OF TRANSACTIONS ID

### ISSUE THREAD

**Issue by marijacin** [virtualeconomy/felix_frontend#45]
Screenshots from figma that are missing:
![image](https://user-images.githubusercontent.com/86068985/151989942-0a4aade2-d01d-4e71-ad81-322493ec8956.png)

![image](https://user-images.githubusercontent.com/86068985/151989997-06a46a6a-0efd-47a4-86e3-14596622464c.png)

**Comment by jwzheng96** [comment]
solved.
