### ISSUE TITLE
TITLE IN TAB

### ISSUE THREAD

**Issue by marijacin** [virtualeconomy/felix_frontend#50]
change current tile "v-words-nft" to "Felix Dictionary" 

![image](https://user-images.githubusercontent.com/86068985/152580191-3698e0a7-7721-43f0-995f-c20d26e7a664.png)

**Comment by jwzheng96** [comment]
solved.

**Comment by marijacin** [comment]
is it not live yet, because at this moment I still don't see it on live page.

**Comment by jwzheng96** [comment]
![image](https://user-images.githubusercontent.com/32029023/153366585-2a65b225-24eb-4b27-9802-bea63a6d190e.png)

**Comment by jwzheng96** [comment]
I think it's already in effect. Please check it
