### ISSUE TITLE
updated footer

### ISSUE THREAD

**Issue by marijacin** [virtualeconomy/felix_frontend#55]
![image](https://user-images.githubusercontent.com/86068985/152587514-532d96de-643a-4f67-9197-f18b1bc4bfc7.png)

**Comment by marijacin** [comment]
set for mobile: no change

**Comment by marijacin** [comment]
Please, check Figma file for mobile. Don't include this footer in mobile, if it's possible.

**Comment by jwzheng96** [comment]
I have removed some parts of footer in mobile
