### ISSUE TITLE
Updated footer

### ISSUE THREAD

**Issue by marijacin** [virtualeconomy/felix_frontend#57]
New features have been added to the footer, per client request. Please check the Figma file for frontend. 

![image](https://user-images.githubusercontent.com/86068985/152644619-8d18c69b-b957-417a-9fb2-d869c0d650af.png)
Peerchemist has code for this already

**Comment by marijacin** [comment]
For mobile: skip this step, leave footer for mobile as it is

**Comment by peerchemist** [comment]
Last minted can be implemented using new API endpoing: `/lastsaved`. It will return the list of last 5 saved words.

**Comment by jwzheng96** [comment]
fixed.
