### ISSUE TITLE
Extension to V Wallet - new message

### ISSUE THREAD

**Issue by marijacin** [virtualeconomy/felix_frontend#62]
As discussed at the meeting, there is a problem when a user has an extension but is not logged in. 
PROBLEM: shows a message to install an extension, although the user already has an extension
SOLUTION: show the new message, asking the user to log in
![image](https://user-images.githubusercontent.com/86068985/153192469-e13b70be-8d6a-4db8-bb1f-f139b7b79d8b.png)

**Comment by Haynar216** [comment]
Bug in Extension wallet. Closed First
