### ISSUE TITLE
Font problems

### ISSUE THREAD

**Issue by marijacin** [virtualeconomy/felix_frontend#86]
Font problems - font should be SEN. Not CLOVES. Months ago was decided to switch to google font. 
https://fonts.google.com/specimen/Sen?query=sen
Maybe this will fix issue #6 https://github.com/virtualeconomy/felix_frontend/issues/6
More on this subject https://developers.google.com/fonts/docs/troubleshooting
Also, please pay attention to where the font is bold, italic, sizes of font, etc…

**Comment by jwzheng96** [comment]
solved.

**Comment by marijacin** [comment]
There are still problems, displaying Times New Roman and Arial font. Can we fix this? The client said, if we can't fix this part, remove underlined words and just leave the arrow back. 
![Untitled-1-02](https://user-images.githubusercontent.com/86068985/156794153-28c69419-fc2c-4a24-9095-0a0bb6529224.jpg)
![Untitled-1-03](https://user-images.githubusercontent.com/86068985/156794170-18158d5f-397b-4a8e-ad40-39e818dff33e.jpg)

**Comment by marijacin** [comment]
Also font in "DONATE" box. ATM it is mixture of Times new Roman and Arial. 
![Untitled-1-04](https://user-images.githubusercontent.com/86068985/156794231-80ca57df-cfdd-4840-a979-0cceb8d0b05a.jpg)

**Comment by marijacin** [comment]
Same goes for SHARE and SEND boxes in gallery.
![Untitled-1-05](https://user-images.githubusercontent.com/86068985/156794423-db40e182-074b-4520-9b68-0edcdb496968.jpg)
![Untitled-1-06](https://user-images.githubusercontent.com/86068985/156794429-ea7dd3e4-783a-4f78-81c9-165b4d193b3b.jpg)

**Comment by jwzheng96** [comment]
solved.

**Comment by jwzheng96** [comment]
Should fon-family be changed to SEN for all text in felix app?

**Comment by jwzheng96** [comment]
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/32029023/156972208-ffb68cb9-d90c-492f-b0d1-88a37d3ae872.png">
