### ISSUE TITLE
CONNECT YOUR WALLET and INSTALL EXTENSION messages

### ISSUE THREAD

**Issue by marijacin** [virtualeconomy/felix_frontend#87]
“To continue minting you must connect your Metamask wallet and have a minimum of 5,000 DARA tokens available.“
“Sorry, but it seems that you don’t have a Metamask extension. To continue, please use the link to install.”
“To continue minting you must connect your V Wallet.“
“Sorry, but it seems that you don’t have a V Wallet extension. To continue, please use the link to install.”

**Comment by Yuxanju** [comment]
It’s important you synchronize your wallet and debug it from hack and malware attacks

**Comment by jwzheng96** [comment]
solved.
