### ISSUE TITLE
Change text in Share dialog

### ISSUE THREAD

**Issue by marijacin** [virtualeconomy/felix_frontend#90]
New text;
“I just saved the #Wiktionary definition of the word IMMUTABLE to #blockchain, and minted a unique #NFT! Check out @FelixDictionary! [www.saveaword.com](http://www.saveaword.com/)”
![image](https://user-images.githubusercontent.com/86068985/156207117-02a1a18c-48e2-4c9c-a33d-aae9ce5c283d.png)

**Comment by jwzheng96** [comment]
solved.
