### ISSUE TITLE
Gallery issues

### ISSUE THREAD

**Issue by marijacin** [virtualeconomy/felix_frontend#93]
1. At the moment, the default is that it shows the first oldest NFTs. Can we switch that so it shows the newest on the top, first?
2. Also, regarding this, can new NFTs, that the user still didn't see in Gallery be orange for 5-10 seconds? So that users see right away that these NFTs are new? For example, if somebody sends them NFTs, they will be orange for just a few seconds, so he will notice them.

**Comment by Xavier-Gao** [comment]
For second issue, the gallery can not refresh automatically when somebody send you NFTs. So we don't know  which the newest NFTs.
